[package]
name = "goemo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
regex = "1.7.0"
scraper = "0.13.0"
ureq = "2.5.0"
